openapi: 3.0.1
info:
  title: RickyMortyAPI definition
  version: v1
servers:
  - url: https://rickandmortyapi.com/api/
paths:
  /character:
    get:
      tags:
        - characters
      operationId: get-characters
      parameters:
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: count
          schema:
            type: integer
      responses:
        '200':
          description: ok
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ModelAPIResponse"
        '400':
          description: Page not found
    servers:
      - url: https://rickandmortyapi.com/api/
components:
  schemas:
    ModelAPIResponse:
      type: object
      properties:
        info:
          type: object
          properties:
            count:
              type: integer
              example: 100
            pages:
              type: integer
              example: 1
            next:
              type: string
              example: "https://rickandmortyapi.com/api/character/?page=2"
            prev:
              type: string
              example: "https://rickandmortyapi.com/api/character/?page=1"
        results:
          type: array
          items:
            $ref: "#/components/schemas/Character"
    Character:
      type: object
      properties:
        id:
          type: integer
          example: 200
        name:
          type: string
          example: "Ricky"
        status:
          type: string
          example: Alive
        species:
          type: string
          example: Humanoid
        type:
          type: string
          example: Rick's Toxic Side
        gender:
          type: string
          example: Male
        episode:
          type: array
          items:
            type: string
        url:
          type: string
          example: www.google.com



