openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /task-one/message:
    post:
      tags:
        - task-one-controller
      operationId: sendMessage
      requestBody:
        content:
          application/json:
            schema:
              type: string
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /task-one/hello-world:
    get:
      tags:
        - task-one-controller
      operationId: helloWorld
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
components: {}
